const textMap: Record<string, string> = {
  valid: "有效",
  type: "类型",
  shape: "形状",
  color: "颜色",
  rawText: "原始文本",
  direction: "方向",
  action: "操作",
  setting: "设置项",
  value: "值",
  composite: "复合图形",
  message: "提示",
  draw: "绘制",
  setting_command: "画笔设置",
  composite_command: "复合绘图",
  action_command: "编辑操作",
  invalid: "无效指令",
  line: "线条",
  circle: "圆形",
  rectangle: "矩形",
  triangle: "三角形",
  arc: "圆弧",
  red: "红色",
  blue: "蓝色",
  green: "绿色",
  yellow: "黄色",
  black: "黑色",
  white: "白色",
  purple: "紫色",
  orange: "橙色",
  horizontal: "横向",
  vertical: "纵向",
  diagonal: "斜向",
  clear: "清空",
  undo: "撤销",
  redo: "重做",
  save: "保存",
  lineWidth: "线宽",
  true: "是",
  false: "否",
  scene: "场景",
  style: "风格",
  operation: "编辑动作",
  drawScene: "绘制场景",
  setStyle: "切换风格",
  editLastObject: "编辑最后一个对象",
  nightCity: "夜晚城市",
  starrySky: "宇宙星空",
  sunsetBeach: "海边日落",
  forest: "森林",
  robot: "机器人",
  neon: "霓虹风格",
  minimal: "极简风格",
  handDrawn: "手绘风格",
  soft: "柔和风格",
  default: "默认风格",
  delete: "删除",
  duplicate: "复制",
  scaleUp: "变大",
  scaleDown: "变小",
  moveLeft: "向左移动",
  moveRight: "向右移动",
  moveUp: "向上移动",
  moveDown: "向下移动",
  setColor: "修改颜色",
  composeScene: "组合场景",
  appendObjects: "追加素材",
  enrichScene: "丰富画面",
  adjustScene: "全局调整",
  custom: "自定义",
  spring: "春天",
  summer: "夏天",
  autumn: "秋天",
  winter: "冬天",
  campus: "校园",
  park: "公园",
  beach: "海边",
  city: "城市",
  space: "太空",
  lakeside: "湖边",
  birthday: "生日",
  night: "夜晚",
  sunset: "日落",
  day: "白天",
  rain: "雨天",
  snow: "雪天",
  child: "儿童画风格",
  watercolor: "水彩风格",
  pixel: "像素风格",
  brighter: "更亮",
  darker: "更暗",
  warmer: "更温暖",
  cooler: "更冷",
};

export function localizeText(value: unknown): string {
  return textMap[String(value)] ?? String(value);
}

export function localizeCommand(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(localizeCommand);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [
        localizeText(key),
        localizeCommand(item),
      ]),
    );
  }
  return typeof value === "string" || typeof value === "boolean" ? localizeText(value) : value;
}
